### ISSUE TITLE
VERSION newline

### ISSUE THREAD

**Issue by vtjnash** [Keno/julia#15]
Chomp only handles unix newlines.  If Julia is checked out with Windows newlines, the parsing of the file VERSION fails.

**Comment by StefanKarpinski** [comment]
Non-UNIX newlines are the worst. Seriously. The WORST!

**Comment by StefanKarpinski** [comment]
Closed by https://github.com/JuliaLang/julia/commit/3d707882655894ccaae26f233de069d730cb36ee. Please verify that my fix works and reopen if not.
