### ISSUE TITLE
openblas installation

### ISSUE THREAD

**Issue by vtjnash** [Keno/julia#20]
LIBBLAS variable expects v0.1.1 suffix, which is not actually present (although I might just have an stale build)

**Comment by Keno** [comment]
Should be fixed (I think). Not sure though. Will try a fresh build later and see if it gets copied properly.

**Comment by vtjnash** [comment]
I changed the LIBBLAS variable to remove the v0.1.1 suffix. If this is working for everyone else, I would like to close this issue.

**Comment by Keno** [comment]
@vtjnash Any objections to closing this?
