### ISSUE TITLE
stack corruption bug on windows

### ISSUE THREAD

**Issue by vtjnash** [Keno/julia#22]
when running the default test suite (in its entirety), the stack gets corrupted at some point during execution of lapack:

lapack.jl
0x03ED0870 (0x00000002 0x00000000 0x00000000 0x3AEEBB33), LAPACKE_csyr_work() + 0x1242A4 bytes(s)
0x03757FDE (0x0028E198 0x0028E19C 0x0028E364 0x0028E2E4), dscal() + 0x8E bytes(s)
0x03A32BB2 (0x00000000 0x0028956C 0x00000001 0x00000000), dhseqr_() + 0x722 bytes(s)
0x775BE38C (0x775BE0F2 0x002897E4 0x0000000C 0x775BE046), RtlInitUnicodeString() + 0x164 bytes(s)
0x775BE38C (0x002897E4 0x0000000C 0x775BE046 0x00000001), RtlInitUnicodeString() + 0x164 bytes(s)
0x775BE0F2 (0x09BAB340 0x002897E4 0x09A30BD4 0x09BAB338), RtlAllocateHeap() + 0xAC bytes(s)
0x775BE023 (0x00330000 0x00000000 0x751698DA 0xF67C1E5D), RtlFreeHeap() + 0x7E bytes(s)
0x751698CD (0x09BAB340 0x099C3CF8 0x0000000C 0x0000528C), free() + 0x39 bytes(s)
0x662328C7 (0x00000000 0x09B08348 0x006F0048 0x006F0160), ares_version() + 0x3C48B bytes(s)
0x775BE38C (0x775BE0F2 0x0000000C 0x0000000C 0x775BE046), RtlInitUnicodeString() + 0x164 bytes(s)
0x775BE38C (0x0000000C 0x0000000C 0x775BE046 0x0000000E), RtlInitUnicodeString() + 0x164 bytes(s)
0x775BE0F2 (0x007DFC48 0x007DC6A8 0x006F0048 0x006F0160), RtlAllocateHeap() + 0xAC bytes(s)
0x66161969 (0x00289BF4 0x05AE00A5 0x0000528E 0x75169D45), jl_gc_collect() + 0x56842D bytes(s)
0x65FEB73E (0x00330000 0x00000000 0x0028977C 0x662585C0), jl_gc_collect() + 0x3F2202 bytes(s)
0x75169D45 (0x002898E4 0x00289760 0x775BE023 0x09BAA980), malloc() + 0x57 bytes(s)
0x662585C0 (0x00000020 0x00000002 0xFFFFFFFE 0x00000000), ares_version() + 0x62184 bytes(s)
0x66258830 (0x00000000 0x00000000 0x00000000 0x002898E4), ares_version() + 0x623F4 bytes(s)
0x662A2CD0 (0x05E90101 0x0A33A5D0 0x663F6B66 0x00000007), ares_version() + 0xAC894 bytes(s)
0x660DF9E5 (0x664F60EC 0x0A44EB84 0x00333624 0x00289F24), jl_gc_collect() + 0x4E64A9 bytes(s)
0x65BD3681 (0x0A442224 0x0028CCF4 0x00000001 0x00000001), jl_dump_function() + 0x15E8 bytes(s)
0x65BE1E00 (0x76F8086D 0x0A434500 0x003301D4 0x00330000), jl_dump_function() + 0xFD67 bytes(s)
0x775BE38C (0x00000000 0x00000000 0x00000000 0x00000000), RtlInitUnicodeString() + 0x164 bytes(s)
0x08000003 (0x00000000 0x00000000 0x00000000 0x00000000) <unknown module>

**Comment by StefanKarpinski** [comment]
Maybe an LAPACK bug or an OpenBLAS bug?

**Comment by vtjnash** [comment]
I don't think any part of that stack is correct. I should clarify that running just the lapack test, without running the other tests in default before it, succeeds.

**Comment by StefanKarpinski** [comment]
Ah. Yes, that does sounds like a Julia-induced memory corruption that LAPACK just happens to stumble into.

**Comment by Keno** [comment]
Ok, this definitely is an LAPACK/OpenBLAS bug as the tests run fine with MKL (in related news we get to use MKL on windows). However, I have no idea how to debug this. Ideas?

/cc @xianyi

**Comment by xianyi** [comment]
Hi,

What's your gcc version? Is Windows 32-bit or 64-bit?

Do you try OpenBLAS 0.2.2 version?

@zchothia , any suggestion?

Thanks

Xianyi

**Comment by Keno** [comment]
This is gcc 4.6.2 on Windows 32-bit using the OpenBLAS develop branch.

**Comment by zchothia** [comment]
A few random thoughts:
- I would have suggested trying a 64-bit build since there would then only be one calling convention involved, but it seems as though this is still a work-in-progress.
- It may be worth trying the reference BLAS and LAPACK implementations to rule out whether OpenBLAS is indeed causing the issue.
- You could try DrMemory [1] although I am uncertain whether this will even work and how helpful it may be since Julia generates code at runtime.
- If all else fails, perhaps you could strategically place print statements to trace the program execution and hopefully isolate the issue in a smaller context.

--Zaheer

[1]: http://code.google.com/p/drmemory/

**Comment by Keno** [comment]
- 64-bit build is not possible at the moment unfortunately
- Both the netlib reference blas/lapack and the intel mkl work fine
- Dr. memory doesn't work
- It's rather hard to narrow done this problem as it seems to not fail on the call that caused the corruption (meaning that there are several different configurations that trigger the same corruption, but taking any of them by themselves does not lead to the corruption)

**Comment by Keno** [comment]
Another option would be to print a trace whenever a ccall is made. @JeffBezanson is that possible/implemented?

**Comment by vtjnash** [comment]
I implemented roughly what loladiro suggested, so here's the stack trace from ./julia test/poly.jl on x86_64 showing the execution of BLAS ccalls leading up to the fault:

ccall in _jl_blas_copy return
ccall in _jl_lapack_syev return
ccall in _jl_lapack_syev return
ccall in _jl_blas_copy return
ccall in _jl_lapack_geev return
ccall _jl_lapack_geev
0x051D0870 (0x00000002 0x00000000 0x00000000 0xB758E4B9), LAPACKE_csyr_work() + 0x1242A4 bytes(s)
0x04A57FDE (0x0028F2A8 0x0028F2AC 0x0028F474 0x0028F3F4), dscal() + 0x8E bytes(s)
0x04D32BB2 (0x77CEE0F2 0x00000009 0x0028F2A8 0x00000000), dhseqr_() + 0x722 bytes(s)
0x77CEE38C (0x00000009 0x0028F2A8 0x00000000 0x00000001), RtlInitUnicodeString() + 0x164 bytes(s)
0x77CEE0F2 (0x00000020 0x00000000 0xFFFFFFFF 0x00000000), RtlAllocateHeap() + 0xAC bytes(s)
0x77CEE38C (0xA12F5401 0x0652C781 0x00000040 0x0066051B), RtlInitUnicodeString() + 0x164 bytes(s)
0x76FF98DA (0x0028AC88 0x00000020 0x00000000 0x00000000), free() + 0x46 bytes(s)
0x61B172AC (0x00000001 0xFFFFFFFF 0x01DFE1F8 0x042A4430), ares_version() + 0x60290 bytes(s)
0x61B5D2C0 (0x0028A988 0x0028A998 0x0028A998 0x01E61648), ares_version() + 0xA62A4 bytes(s)
0x618AD058 (0x0028A998 0x0028A998 0x01E61648 0x00000005), jl_gc_new_weakref() + 0x3F716C bytes(s)
0x0028A988 (0x0028A998 0x01E61648 0x00000005 0x0000001F) <unknown module>
0x0028A998 (0x01E61648 0x00000061 0x00000000 0x01E5EF68) <unknown module>
0x6191DB3E (0x0028ADD8 0x00000020 0x01E61648 0x618AC2F2), jl_gc_new_weakref() + 0x467C52 bytes(s)
0x61B172AC (0x0028AEE8 0x0028ADA8 0x00000020 0x61B5D2C0), ares_version() + 0x60290 bytes(s)
0x618AC2F2 (0x00000000 0xFFFFFFFF 0x00000001 0x0647D77C), jl_gc_new_weakref() + 0x3F6406 bytes(s)
0x61B5D2C0 (0x0647DB6C 0x00000004 0x00000000 0x00000000), ares_version() + 0xA62A4 bytes(s)

And here's the parameters of the last two ccalls:

```
dgeev_(
N, V, 5,
 5x5 Float64 Array:
 0.456784  -0.0456074  0.00153222  -1.56172e-5  3.8561e-8
 1.0        0.0        0.0          0.0         0.0
 0.0        1.0        0.0          0.0         0.0
 0.0        0.0        1.0          0.0         0.0
 0.0        0.0        0.0          1.0         0.0      ,
 5,
 [0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0],
 5x0 Float64 Array,
 5,
 5x5 Float64 Array:
 9.74539e-287  9.74591e-287  1.62667e-286  1.62677e-286  1.62707e-286
 9.74567e-287  9.74603e-287  1.62669e-286  1.62678e-286  1.62709e-286
 9.74575e-287  9.74615e-287  1.62671e-286  1.62701e-286  1.6267e-286
 9.74583e-287  9.74611e-287  1.62673e-286  1.62702e-286  1.62714e-286
 9.74595e-287  9.74631e-287  1.62674e-286  1.62704e-286  3.8103e-316 ,
 5,
 [1.71505e-299],
 -1,
 [31893456]
)
```

```
dgeev_(
N, V, 5,
 5x5 Float64 Array:
 0.456784  -0.0456074  0.00153222  -1.56172e-5  3.8561e-8
 1.0        0.0        0.0          0.0         0.0
 0.0        1.0        0.0          0.0         0.0
 0.0        0.0        1.0          0.0         0.0
 0.0        0.0        0.0          1.0         0.0      ,
 5,
 [0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0],
 5x0 Float64 Array,
 5,
 5x5 Float64 Array:
 9.74539e-287  9.74591e-287  1.62667e-286  1.62677e-286  1.62707e-286
 9.74567e-287  9.74603e-287  1.62669e-286  1.62678e-286  1.62709e-286
 9.74575e-287  9.74615e-287  1.62671e-286  1.62701e-286  1.6267e-286
 9.74583e-287  9.74611e-287  1.62673e-286  1.62702e-286  1.62714e-286
 9.74595e-287  9.74631e-287  1.62674e-286  1.62704e-286  3.8103e-316 ,
 5,
 [1.36256e-299, 1.33508e-299, 1.34846e-299  ...  1.36249e-299, 1.33568e-299],
 170,
 [0]
)
```

**Comment by Keno** [comment]
@zchothia @xianyi any ideas given this trace?

**Comment by vtjnash** [comment]
Note that the 5x5 input array is composed of the following exact fractions:

```
 12187//26680  -8761//192096  883//576288  -1//64032  1//25932960
     1//1          0//1         0//1        0//1      0//1       
     0//1          1//1         0//1        0//1      0//1       
     0//1          0//1         1//1        0//1      0//1       
     0//1          0//1         0//1        1//1      0//1   
```

**Comment by xianyi** [comment]
Hi @vtjnash ,

What's your CPU?  Is it sandy bridge?

Xianyi

**Comment by vtjnash** [comment]
Yes, my system is running in a VM on a sandy bridge (Core i7 2620M). However, I'm currently having build issues that are making it tough for me to do additional testing on this, but @loladiro indicate he may have time today and is also able to reproduce this issue.

**Comment by xianyi** [comment]
Hi @vtjnash ,

Could you build OpenBLAS with NEHALEM target? For example, make TARGET=NEHALEM.

Then, try to reproduce this error.

Thanks

Xianyi

**Comment by vtjnash** [comment]
Unless I made some mistake in compiling, TARGET=NEHALEM and TARGET=PENRYN also fail, but TARGET=COPPERMINE succeeds. (on a side note, TARGET=NOCONA didn't seem to be recognized and instead started compiling for SANDYBRIDGE)

On a different, AMD-64, machine, TARGET=BARCELONA also fails, but with a slightly different stack trace.

If I build with DYNAMIC_ARCH=1, is there a easier / faster way to test different architectures than rebuilding for each target?

**Comment by Keno** [comment]
@xianyi @zchothia We're beginning to think that this is memory/stack alignment issue where OpenBLAS makes an assumption that is not necessarily true on Windows. We're not quite sure what exactly is going wrong but maybe you have any ideas given that information. Also, does OpenBLAS have any kind of assertions that check for alignment that I could enable?

**Comment by xianyi** [comment]
Hi @vtjnash , @loladiro ,

Please test this issue with single thread. For example, export OPENBLAS_NUM_THREADS=1.

Sorry, we didn't implement this assertion. dcopy and dscale are BLAS 1 functions. We implement the kernels in assembly language.

@zchothia , can we debug this in windows? Or, we can generate the core file.

**Comment by Keno** [comment]
In this case OpenBLAS was built without threads anyway so that shouldn't be an issue.

**Comment by xianyi** [comment]
Hi @loladiro ,

I think you need to narrow down the function. 
For example, you can try building BLAS 2 & 3 of OpenBLAS and BLAS 1 of reference BLAS.  

Thanks

Xianyi
