### ISSUE TITLE
realpath on windows

### ISSUE THREAD

**Issue by vtjnash** [Keno/julia#23]
mingw doesn't have realpath

**Comment by JeffBezanson** [comment]
Not to mention everything else in file.jl!

**Comment by Keno** [comment]
There's [GetFullPathName](http://msdn.microsoft.com/en-us/library/windows/desktop/aa364963%28v=vs.85%29.aspx) and a lot of file.jl can be implemented using libuv. I'll have a crack at that over the weekend (unless somebody else wants to do that first).
