### ISSUE TITLE
getenv regression between 17f50ea4e0 and f6f74ebea7

### ISSUE THREAD

**Issue by ihnorton** [Keno/julia#29]
> |  Commit 17f50ea4e0 (2012-08-15 22:30:58)
> |__/                   |
> 
> julia> get(ENV, "JULIA_EDITOR", "emacs")
> "vim"

vs:

> |  Commit f6f74ebea7 (2012-09-03 19:58:22)*
> |__/                   |
> 
> julia> get(ENV, "JULIA_EDITOR", "emacs")
> "vim\0"

**Comment by ihnorton** [comment]
This breaks at least edit(".."), with the following error:

> julia> edit("test.jl")
> Invalid JULIA_EDITOR value: "vim\0"

Rather inelegant temporary solution, added in env.jl \@windows_only accessEnv:

``` julia
strlen(a::Array{Uint8}) = ccall(:u8_strlen, Int, (Ptr{Uint8},), a)
conv_charstr(a::Array{Uint8,1}) = bytestring( a[1:strlen(a)] )
```

**Comment by StefanKarpinski** [comment]
Factoid that may or not be helpful: there is an extra byte allocated for every `Array{Uint8}` that is set to `0x0` so that if you use a byte array as a string passed to C it will always be NUL-terminated. Hence the allocated length of a byte array is one greater than the number of bytes it looks like it actually is. Only byte arrays work like this.

**Comment by ihnorton** [comment]
Thanks, I think that's it. 4ceda8a fixes it for me, but It's not entirely clear to me why bytestring() didn't chomp it down.. array.c:310 jl_pchar_to_string calls strlen which should have taken care of it, I think.

**Comment by ihnorton** [comment]
Mistyped above - meant jl_cstr_tostring.

Tracing down from which() output, it makes sense now: bytestring(a, len) is calling jl_pchar_to_string with a fixed length which is +1 beyond the NUL ending.

**Comment by Keno** [comment]
Fixed by @ihnorton's pull request. Thanks!

**Comment by ihnorton** [comment]
Cool, thanks.  This default behavior for bytestring(Array) is kind of confusing.

**Comment by StefanKarpinski** [comment]
> Cool, thanks. This default behavior for bytestring(Array) is kind of confusing.

How so? It's evolved over time and feedback on any confusion the current version causes would be good to know.

**Comment by ihnorton** [comment]
> How so? It's evolved over time and feedback on any confusion the current version causes would be good to know.

Well, I naively expected that bytestring(Ptr{Uint8}) and bytestring(Array{Uint8,1}) would have the same behavior: namely, pulling a null-terminated string from some memory block. However, the former stops at 0x0, while the latter dumps the whole array. This is unhelpful for the common case of an Array(Uint8, N) passed to ccall (to a function expecting char*).

Tracing this out has actually been good for me - but I want to know what's going on under the hood. Generally I think it would be useful to have a built-in function that consistently pulls out a null-terminated string for various inputs. Apologies if I've missed it.

Now I have this helper at the top of my script:

cstring(a::Array{Uint8,1}) = ccall(:jl_cstr:to_str, ByteString, (Ptr{Uint8},), a)

**Comment by JeffBezanson** [comment]
It is defensible to use the name `cstring` for any function that assumes or does anything about trailing 0 bytes.
