### ISSUE TITLE
ctrl-c handler doesn't get called

### ISSUE THREAD

**Issue by vtjnash** [Keno/julia#3]
SIGINT is being ignored (instead of calling our signal handler) except at the REPL prompt

**Comment by Keno** [comment]
I think I got this figured out. Will push in a minute.

**Comment by vtjnash** [comment]
Whoops, I did too and just pushed. I'm curious if we did it similar or if you have a better approach.

**Comment by Keno** [comment]
Ok, it took a little longer than expected, but I just pushed it. Try it out!

**Comment by Keno** [comment]
Seems like I broke something during the merge. A fix is underway

**Comment by Keno** [comment]
done

**Comment by vtjnash** [comment]
I am SO confused right now. Everything is working, but you reverted the changes I made and made them raw reads again, but those aren't working through readline (it would segfault if they were since the async handler isn't setup) so that means the interrupt is suddenly working properly. I don't know, but I'm thinking of removing the repl-readline code dealing with them and just leave the signal handlers.

**Comment by Keno** [comment]
Yes, it was a problem with the terminal settings. Readline is only active during the prompt (I suppose whoever implemented that wanted to be able to read from STDIN outside the REPL).
