### ISSUE TITLE
Wait

### ISSUE THREAD

**Issue by vtjnash** [Keno/julia#37]
Implementation of various wait calls needs to be fixed to not busy-wait.

**Comment by vtjnash** [comment]
closed with eafb5654512d40866ae6431d27511041f1c7fe2f

**Comment by ViralBShah** [comment]
Would it be better to do some of these things directly on the main julia repo? Just trying to understand if we can start mainstreaming some of this stuff.

**Comment by vtjnash** [comment]
This patch has no relevance in the main julia repo currently. This was one of a small set of fixes (and the last major one, IIRC) that Jeff had requested to get closer to the merge for the libuv fork.
