### ISSUE TITLE
readall after SIGINT is unpredictable

### ISSUE THREAD

**Issue by vtjnash** [Keno/julia#4]
readall will not necessary return after the correct child terminates after SIGINT has been called during prior call to readall. Instead it may return too soon, resulting in the loss of the output text.

**Comment by Keno** [comment]
Can you give me an example of what you mean?

**Comment by vtjnash** [comment]
Let me know if this clear enough. Note that the second call to sleep was canceled immediately with a Ctrl-C. The third call was not. We see that subsequent calls detect that the earlier call finished (before or after they launch) and return thinking their process was done. Calling read_event_loop() repeatedly eventually resynchronizes the machinery.

```
julia> @time readall(`sleep 10`)
elapsed time: 10.033342123031616 seconds


julia> @time readall(`sleep 10`)
^C
 in readall at stream.jl:373
 in readall at stream.jl:366

julia> @time readall(`sleep 10`)
elapsed time: 0.0027670860290527344 seconds


julia> ^C

julia> @time readall(`git --version`)
elapsed time: 0.0024650096893310547 seconds


julia> @time readall(`git --version`)
elapsed time: 0.0024061203002929688 seconds


julia> @time readall(`date`)
elapsed time: 0.011266946792602539 seconds


julia> readall(`date`)


julia> readall(`date`)


julia> readall(`date`)


julia> run_event_loop()

julia> readall(`date`)
Sun Apr  1 03:35:33 EDT 2012


julia> @time readall(`date`)
elapsed time: 0.003509998321533203 seconds
Sun Apr  1 03:36:45 EDT 2012


julia> 

```

**Comment by Keno** [comment]
Fixed
