### ISSUE TITLE
jl_write

### ISSUE THREAD

**Issue by vtjnash** [Keno/julia#52]
is buf->base protected from garbage collection during a jl_write?

**Comment by Keno** [comment]
No (unless otherwise rooted, e.g. the data being pointed to is an array that is a member of the stream).

**Comment by vtjnash** [comment]
I could make a global linked list of write buffers with the pointer to the next and last linked list items tacked on the end of the jl_write_t memory buffer (there's an example of this in the libuv manual). Then insert, removal, and walking would all be O(1).

Do you have any other ideas?
