### ISSUE TITLE
[libuv] typo in windows build

### ISSUE THREAD

**Issue by vtjnash** [Keno/julia#6]
there should be an extra } before this line:
https://github.com/loladiro/libuv/blob/master/src/win/process.c#L986

(Sorry, I can't mark anything in that repo to report this)

**Comment by Keno** [comment]
Yes, I know I fixed it locally. I'm currently building a package. There are a few other issues too that I fixed

**Comment by Keno** [comment]
Done in loladiro/libuv@faaaa0347fda18902aab02a35c6a584d01a41d21
